name: CI

on:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
    branches:
      - "master"
      - "main"
  schedule:
    # Run by default Sunday morning at 3:30:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "30 3 * * 0"

jobs:
  lint:
    name: Lint ubuntu-latest Py3.8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        environment-file: devtools/conda-envs/test_env.yaml
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Run linters
      shell: bash -l {0}
      run: |
        flake8 reference_handler
        yapf --diff --recursive reference_handler
      
  test:
    name: Test ${{ matrix.os }} Py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/test_env.yaml
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --cov=reference_handler --cov-report=xml --color=yes reference_handler/tests/
    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
